import { db } from "@/lib/db";
import { memories, profiles, users } from "@/lib/db/schema";
import { eq, and, inArray, desc } from "drizzle-orm";
import { countTokens } from "./extraction";
import type { MemoryCategory } from "@/lib/db/schema";

interface WakePromptResult {
  prompt: string;
  tokenCount: number;
  memoryCount: number;
  categories: MemoryCategory[];
}

export async function generateWakePrompt(
  profileId: string,
  categories: MemoryCategory[],
  budget: number
): Promise<WakePromptResult> {
  // Get profile name
  const profile = await db.query.profiles.findFirst({
    where: eq(profiles.id, profileId),
  });

  const profileName = profile?.name ?? "this person";

  // Fetch memories by category, sorted by importance
  const selectedMemories = await db.query.memories.findMany({
    where: and(
      eq(memories.profileId, profileId),
      inArray(memories.category, categories)
    ),
    orderBy: [desc(memories.importance), desc(memories.createdAt)],
  });

  // Build sections, respecting token budget
  let totalTokens = 0;
  const sections: Record<MemoryCategory, string[]> = {
    emotional: [],
    work: [],
    hobbies: [],
    relationships: [],
    preferences: [],
  };

  // Preamble tokens (rough estimate)
  const preamble = `You are starting a conversation with someone you know well. Here is what you remember about them:\n\n## About ${profileName}\n\n`;
  totalTokens += countTokens(preamble);

  // Footer tokens
  const footer = `\n---\nUse this context naturally. Don't list facts back. Don't say "I remember that..." — just know it. Reference memories when relevant, especially emotional ones. Be warm and aware.`;
  totalTokens += countTokens(footer);

  // Pack memories by importance until budget
  for (const memory of selectedMemories) {
    const line = memory.emotionalSignificance
      ? `- ${memory.factualContent}\n  → ${memory.emotionalSignificance}`
      : `- ${memory.factualContent}`;

    const lineTokens = countTokens(line);

    if (totalTokens + lineTokens > budget) break;

    sections[memory.category as MemoryCategory].push(line);
    totalTokens += lineTokens;
  }

  // Assemble prompt
  const sectionHeaders: Record<MemoryCategory, string> = {
    emotional: "### Emotional Context\nThese are sensitive topics. Handle with care and awareness.\n",
    work: "### Work & Projects\n",
    hobbies: "### Hobbies & Interests\n",
    relationships: "### Relationships\n",
    preferences: "### Preferences\n",
  };

  let prompt = preamble;

  const categoryOrder: MemoryCategory[] = [
    "emotional",
    "work",
    "hobbies",
    "relationships",
    "preferences",
  ];

  let memoryCount = 0;

  for (const cat of categoryOrder) {
    if (sections[cat].length > 0) {
      prompt += sectionHeaders[cat];
      prompt += sections[cat].join("\n") + "\n\n";
      memoryCount += sections[cat].length;
    }
  }

  prompt += footer;
  prompt += `\n\nToken count: ${totalTokens} | Memories: ${memoryCount} | Generated by Ember`;

  return {
    prompt,
    tokenCount: totalTokens,
    memoryCount,
    categories,
  };
}
